spring.application.name=dbh-api
server.port=8001

server.forward-headers-strategy=framework
management.tracing.sampling.probability=1

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

command.api.host=http://localhost:9999/dbh-command-api/
command.api.path=dbh-employee-command

query.api.host=http://localhost:9999/dbh-query-api/
query.api.path=dbh-employee-query
